### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by sdemura** [sublimelsp/LSP-pyls#11]
Hello,

While the README doesn't mention MacOS support, I was able to get this working just fine by cloning this repo into my Sublime Packages directory.

Thanks for the nice work on this!

**Comment by rchl** [comment]
It mentions OSX which is mac but I guess the official nomenclature is macOS these days.

**Comment by rchl** [comment]
Committed change to master: https://github.com/sublimelsp/LSP-pyls/commit/81dd23d2f2b4b54720d8cfc54b2f0d7fea0fd563
