### ISSUE TITLE
Error on install when "wheels" is missing

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-pyls#18]
My python has updated through `brew` and now I'm getting this:

![Screenshot 2020-12-07 at 21 24 15](https://user-images.githubusercontent.com/153197/101401383-8fb19680-38d2-11eb-9dfc-ea86ec845b6b.png)

I haven't tried fixing it yet but it's not a great message to show in the user's face.

According to https://github.com/allenai/document-qa/issues/47 I might have to install some dependencies globally but that doesn't sound like a good solution.

**Comment by rchl** [comment]
@rwols do you have any idea for how to solve this nicely. If we could avoid building at all, that would be nice since it's quite CPU-heavy process.

**Comment by rwols** [comment]
Nothing comes to mind :)

**Comment by rchl** [comment]
MacOS 11-specific bug and fixed 5 days ago in cpython...
https://github.com/python/cpython/commit/5291639e611dc3f55a34666036f2c3424648ba50

**Comment by rchl** [comment]
Cpython Version with the fix is already available so we can close this.
