### ISSUE TITLE
No linter diagnostics reported

### ISSUE THREAD

**Issue by Dracyr** [sublimelsp/LSP-pyls#21]
Hey! Trying to use LSP-pyls in a project, I can get code completion working, but not any of the linters 

* Running on Mac
* LSP version 1.2.12
* Sublime Text 4099
* Using poetry for package/venv management
* I have no user-visible errors

User settings file
```json
// Settings in here override those in "LSP-pyls/LSP-pyls.sublime-settings"

{
  "settings": {
    "pyls.configurationSources": ["flake8"],
    "pyls.plugins.pycodestyle.enabled": false,
    "pyls.plugins.flake8_lint.enabled": true,
    "pyls.plugins.pyls_mypy.enabled": true,
    "pyls.plugins.pyls_mypy.live_mode": false,
    "pyls.plugins.pyls_black.enabled": true,
    "pyls.plugins.pyls_isort.enabled": true,
  },
}

```

## What I expect

To get mypy/flake8 warnings/diagnostics shown in Sublime.
Renames, code-completion and go-to-reference is working, the things I expect are depending on JEDI.

## What I've tried

Enabling the different linters from the overall lsp settings under the pyls key, the lsp-pyls settings, and project settings.
Since I'm using poetry, I thought something might be up with the PATH vars, to I tried adding the env section to these different locations as well, but it didn't work either.

```
  "env": {
    "PYTHONPATH": "$sublime_py_files_dir:$packages:/Users/username/Library/Caches/pypoetry/virtualenvs/backend-GAy6QZlK-py3.8",
    "MYPY_PATH": "$sublime_py_files_dir:$packages:/Users/username/Library/Caches/pypoetry/virtualenvs/backend-GAy6QZlK-py3.8"
  },
```

**Comment by rwols** [comment]
Works for me

<img width="537" alt="image" src="https://user-images.githubusercontent.com/2431823/111905550-821cb880-8a4c-11eb-860b-d0d1378fa396.png">

with these settings:

```js
// Settings in here override those in "LSP-pyls/LSP-pyls.sublime-settings"
{
    "settings": {
        "pyls.configurationSources": [
            "flake8"
        ],
        "pyls.plugins.pycodestyle.enabled": false,
        "pyls.plugins.flake8_lint.enabled": true
    }
}
```

Do you perhaps have diagnostics turned off in Packages/User/LSP.sublime-settings?

**Comment by Dracyr** [comment]
Yeah, I expect something is up with my specific setup here.

No, these are my fairly minimal settings.
```json
// Settings in here override those in "LSP/LSP.sublime-settings"
{
  "log_debug": true,
  "log_stderr": true,
  "log_server": ["panel"],
  "show_diagnostics_panel_on_save": 1,
}
```

If I enable pyflakes or pycodestyle (still with `"pyls.configurationSources": ["flake8"]` , then I get diagnostics from them, but flake8 isn't working. Looking at the exposed config for the vscode version [1]  the option `pyls.plugins.flake8_lint.enabled` also doesn't seem to be exposed 🤔 

And for mypy, I expect there's something up with my PYTHONPATH/MYPY_PATH, when I change the settings to explicitly include the project venv, It starts showing me type-errors. But it also can't find the implementations for the libraries/modules in that venv folder...
```
// Settings in here override those in "LSP-pyls/LSP-pyls.sublime-settings"
{
  "settings": { ... },
  // After adding this, mypy starts showing results
  "env": {
    "PYTHONPATH": "/Users/<some-long-path>/backend/.venv/lib/python3.8/site-packages",
    "MYPY_PATH": "/Users/<some-long-path>/backend/.venv/lib/python3.8/site-packages",
  }
}
```

So I think I probably have two different issues on my hand.

1. https://github.com/palantir/python-language-server/blob/develop/vscode-client/package.json

**Comment by rchl** [comment]
It seems the option is actually called `"pyls.plugins.flake8.enabled": true,`. I've updated schema on master to use that since I can only make it work with that one.

**Comment by Dracyr** [comment]
Aha! Yeah, setting `"pyls.plugins.flake8.enabled": true,` works on my end as well. 
As for the mypy stuff, I think I just have to sort out all the proper PATH/PYTHONPATH/MYPYPATH settings in my environment. 

Thanks for the help! I'll go ahead and close this now then 😃
