### ISSUE TITLE
Remove cache data on unloading

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-pyls#3]
Like other LSP packages do, this one should also remove the cache data on `plugin_unloaded` so that it cleans after itself when uninstalled or on updating.

**Comment by rwols** [comment]
Hmm, why is this the right approach? Any cache data from .sublime-syntax files also remains $DATA/Cache after removing a package for example.

**Comment by rchl** [comment]
It would be good to clean up on uninstall of the package as nothing else will do that.

I understand that you might not want to clean up on updating the package though and you probably can't tell those apart.

But cleaning up on update might be a healthy thing to do to "reset" stuff just in case.

**Comment by rchl** [comment]
This is now handled by the `PipClientHandler`.
